<a href="https://colab.research.google.com/github/giovannadk/WSDKW/blob/main/Tratamento_de_dados_ATV_4%C2%BA_SEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Começo do código, importando a biblioteca PANDAS e montando todo o caminho do arquivo

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
origem = '/content/drive/My Drive/Data/COMEXSTAT/'

Identificando e simplificando o nome dos arquivos para preparar e nomear cada informação que consta no banco de dados dos dois arquivos.

In [ ]:
arquivo_1 = origem + 'materiais.csv'
arquivo_2 = origem + 'movimentacoes.csv'

In [ ]:
materiais = pd.read_csv(arquivo_1,low_memory=False,sep=',',encoding='UTF-8')
movimentacoes = pd.read_csv(arquivo_2,low_memory=False,sep=',',encoding='UTF-8')

In [ ]:
materiais.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cod_material       5 non-null      object
 1   descricao          5 non-null      object
 2   lead_time_dias     5 non-null      int64
 3   consumo_medio_dia  5 non-null      int64
 4   lote_minimo        5 non-null      int64
 5   custo_unitario     5 non-null      float64
dtypes: float64(1), int64(3), object(2)
memory usage: 372.0+ bytes

In [ ]:
movimentacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670 entries, 0 to 669
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mov        670 non-null    int64
 1   data          670 non-null    object
 2   cod_material  670 non-null    object
 3   tipo          670 non-null    object
 4   quantidade    670 non-null    int64
 5   observacao    670 non-null    object
dtypes: int64(2), object(4)
memory usage: 31.5+ KB

Aqui vai ter uma tabela dos dois arquivos só para análise de estrutura.

In [ ]:
materiais.head(10)

,cod_material,descricao,lead_time_dias,consumo_medio_dia,lote_minimo,custo_unitario
0,M001,Rolamento 6203,7,6,100,18.5
1,M002,Correia V A-42,10,3,60,42.0
2,M003,Parafuso M8x40 (cx),5,12,150,3.2
3,M004,Óleo hidráulico 20L,14,2,30,210.0
4,M005,Filtro de ar industrial,8,2,40,55.0

In [ ]:
movimentacoes.head(10)

   id_mov        data cod_material     tipo  quantidade        observacao
0       1  2025-01-01         M001  ENTRADA         120     Saldo inicial
1       2  2025-01-01         M002  ENTRADA          80     Saldo inicial
2       3  2025-01-01         M003  ENTRADA         200     Saldo inicial
3       4  2025-01-01         M004  ENTRADA          40     Saldo inicial
4       5  2025-01-01         M005  ENTRADA          60     Saldo inicial
5       6  2025-01-02         M001    SAIDA           7  Consumo produção
6       7  2025-01-02         M002    SAIDA           3  Consumo produção
7       8  2025-01-02         M003    SAIDA           7  Consumo produção
8       9  2025-01-02         M005    SAIDA           2  Consumo produção
9      10  2025-01-03         M001    SAIDA           6  Consumo produção

Código para relacionar os dois arquivos a fim de traduzir o código do material para a sua seguinte descrição.

In [ ]:
exp_final = movimentacoes.merge(materiais[['cod_material','descricao']],on='cod_material',how='left')

In [ ]:
exp_final.head(10)

,id_mov,data,cod_material,tipo,quantidade,observacao,descricao
0,1,2025-01-01,M001,ENTRADA,120,Saldo inicial,Rolamento 6203
1,2,2025-01-01,M002,ENTRADA,80,Saldo inicial,Correia V A-42
2,3,2025-01-01,M003,ENTRADA,200,Saldo inicial,Parafuso M8x40 (cx)
3,4,2025-01-01,M004,ENTRADA,40,Saldo inicial,Óleo hidráulico 20L
4,5,2025-01-01,M005,ENTRADA,60,Saldo inicial,Filtro de ar industrial
5,6,2025-01-02,M001,SAIDA,7,Consumo produção,Rolamento 6203
6,7,2025-01-02,M002,SAIDA,3,Consumo produção,Correia V A-42
7,8,2025-01-02,M003,SAIDA,7,Consumo produção,Parafuso M8x40 (cx)
8,9,2025-01-02,M005,SAIDA,2,Consumo produção,Filtro de ar industrial
9,10,2025-01-03,M001,SAIDA,6,Consumo produção,Rolamento 6203

Código para relacionar os dois arquivos a fim de incluir todas as colunas citadas abaixo e trazer automático a informação conforme o código do material.

In [ ]:
exp_final = movimentacoes.merge(materiais[['cod_material','descricao', 'lead_time_dias', 'consumo_medio_dia', 'lote_minimo', 'custo_unitario']],on='cod_material',how='left')

In [ ]:
exp_final.head(10)

,id_mov,data,cod_material,tipo,quantidade,observacao,descricao,lead_time_dias,consumo_medio_dia,lote_minimo,custo_unitario
0,1,2025-01-01,M001,ENTRADA,120,Saldo inicial,Rolamento 6203,7,6,100,18.5
1,2,2025-01-01,M002,ENTRADA,80,Saldo inicial,Correia V A-42,10,3,60,42.0
2,3,2025-01-01,M003,ENTRADA,200,Saldo inicial,Parafuso M8x40 (cx),5,12,150,3.2
3,4,2025-01-01,M004,ENTRADA,40,Saldo inicial,Óleo hidráulico 20L,14,2,30,210.0
4,5,2025-01-01,M005,ENTRADA,60,Saldo inicial,Filtro de ar industrial,8,2,40,55.0
5,6,2025-01-02,M001,SAIDA,7,Consumo produção,Rolamento 6203,7,6,100,18.5
6,7,2025-01-02,M002,SAIDA,3,Consumo produção,Correia V A-42,10,3,60,42.0
7,8,2025-01-02,M003,SAIDA,7,Consumo produção,Parafuso M8x40 (cx),5,12,150,3.2
8,9,2025-01-02,M005,SAIDA,2,Consumo produção,Filtro de ar industrial,8,2,40,55.0
9,10,2025-01-03,M001,SAIDA,6,Consumo produção,Rolamento 6203,7,6,100,18.5

Esse código está preparando e organizando os dados da tabela exp_final pela data e pelo material para futuramente calcular o trabalho de estoque.

In [ ]:
import pandas as pd
exp_final['data'] = pd.to_datetime(exp_final['data'])
exp_final.sort_values(by=['cod_material', 'data'], inplace=True)

Agora, vamos calcular o movimento de estoque diário (entrada and saida) para cada material e depois o saldo de estoque acumulado.

In [ ]:
import pandas as pd
estoque_df = pd.DataFrame()

for material_code in exp_final['cod_material'].unique():
    material_df = exp_final[exp_final['cod_material'] == material_code].copy()

    # Get unique dates for this material
    min_date = material_df['data'].min()
    max_date = material_df['data'].max()
    full_date_range = pd.date_range(start=min_date, end=max_date, freq='D')

    # Create a daily summary for this material
    daily_summary = pd.DataFrame({'data': full_date_range, 'cod_material': material_code})

    # Calculate daily entries and exits
    entradas_dia = material_df[material_df['tipo'] == 'ENTRADA'].groupby('data')['quantidade'].sum().reindex(full_date_range, fill_value=0)
    saidas_dia = material_df[material_df['tipo'] == 'SAIDA'].groupby('data')['quantidade'].sum().reindex(full_date_range, fill_value=0)

    daily_summary['entradas_dia'] = entradas_dia.values
    daily_summary['saidas_dia'] = saidas_dia.values

    # Calculate accumulated stock
    initial_stock_row = material_df[(material_df['data'] == min_date) & (material_df['observacao'] == 'Saldo inicial')]
    if not initial_stock_row.empty:
        current_stock = initial_stock_row['quantidade'].sum() # Sum if multiple initial entries on the same day
    else:
        current_stock = 0

    accumulated_stock = []
    for index, row in daily_summary.iterrows():
        current_stock += row['entradas_dia'] - row['saidas_dia']
        accumulated_stock.append(current_stock)

    daily_summary['saldo_estoque_acumulado'] = accumulated_stock

    # Merge material details (lead_time_dias, consumo_medio_dia, lote_minimo, custo_unitario, descricao)
    material_info = material_df[['cod_material', 'descricao', 'lead_time_dias', 'consumo_medio_dia', 'lote_minimo', 'custo_unitario']].drop_duplicates()
    daily_summary = pd.merge(daily_summary, material_info, on='cod_material', how='left')

    estoque_df = pd.concat([estoque_df, daily_summary])

estoque_df.reset_index(drop=True, inplace=True)
display(estoque_df.head())

,data,cod_material,entradas_dia,saidas_dia,saldo_estoque_acumulado,descricao,lead_time_dias,consumo_medio_dia,lote_minimo,custo_unitario
0,2025-01-01,M001,120,0,240,Rolamento 6203,7,6,100,18.5
1,2025-01-02,M001,0,7,233,Rolamento 6203,7,6,100,18.5
2,2025-01-03,M001,0,6,227,Rolamento 6203,7,6,100,18.5
3,2025-01-04,M001,0,0,227,Rolamento 6203,7,6,100,18.5
4,2025-01-05,M001,0,8,219,Rolamento 6203,7,6,100,18.5

Agora, vamos calcular o Estoque de Segurança, o Ponto de Pedido (PP), o Lote de Reposição para cada material. Vamos identificar também os dias no qual o estoque cai para um número menor do que o ponto de pedido ou fica em zero/negativo.

In [ ]:
import pandas as pd
# Calculate Safety Stock (Estoque de Segurança)
# Assuming Safety Stock = Lead Time (days) * Average Daily Consumption
estoque_df['estoque_seguranca'] = estoque_df['lead_time_dias'] * estoque_df['consumo_medio_dia']

# Calculate Reorder Point (Ponto de Pedido)
# Assuming Reorder Point = (Lead Time (days) * Average Daily Consumption) + Safety Stock
estoque_df['ponto_pedido'] = (estoque_df['lead_time_dias'] * estoque_df['consumo_medio_dia']) + estoque_df['estoque_seguranca']

# Lote de Reposição (Reorder Lot) is the lote_minimo
estoque_df['lote_reposicao'] = estoque_df['lote_minimo']

# Identify days when stock fell below the Reorder Point
estoque_df['abaixo_pp'] = estoque_df['saldo_estoque_acumulado'] < estoque_df['ponto_pedido']

# Identify days when stock was zero or negative
estoque_df['estoque_zerado_negativo'] = estoque_df['saldo_estoque_acumulado'] <= 0

display(estoque_df.head(10))

,data,cod_material,entradas_dia,saidas_dia,saldo_estoque_acumulado,descricao,lead_time_dias,consumo_medio_dia,lote_minimo,custo_unitario,estoque_seguranca,ponto_pedido,lote_reposicao,abaixo_pp,estoque_zerado_negativo
0,2025-01-01,M001,120,0,240,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
1,2025-01-02,M001,0,7,233,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
2,2025-01-03,M001,0,6,227,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
3,2025-01-04,M001,0,0,227,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
4,2025-01-05,M001,0,8,219,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
5,2025-01-06,M001,0,0,219,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
6,2025-01-07,M001,0,7,212,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
7,2025-01-08,M001,0,5,207,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
8,2025-01-09,M001,0,0,207,Rolamento 6203,7,6,100,18.5,42,84,100,False,False
9,2025-01-10,M001,0,0,207,Rolamento 6203,7,6,100,18.5,42,84,100,False,False

Código para exportar o arquivo final para minha pasta do drive.

In [ ]:
# Export the DataFrame to a CSV file
output_file = origem + 'estoque_df.csv'
estoque_df.to_csv(output_file, index=False, encoding='UTF-8')
print(f"DataFrame exported to: {output_file}")

DataFrame exported to: /content/drive/My Drive/Data/COMEXSTAT/exp_final.csv

**FIM DO CÓDIGO**